branches:
  only:
  - master
  - develop
language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install .
script:
- python3 -m unittest discover
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: fZXEpe1ivG5Xp3dR+AnwbdjtDClBSdkurL5+OIZgLsc5y/k0fbhGCa9eqBF3LSXx+dvuoIGFkS4Nrbmc6vvxOzlE4vB/Ad1lm9rrPTByTcMfxl9UA2E9hXL5mxeW6ppgy2dmlsdfmMh7QiRQVzFg4IwGK3nxyOWTNj6tZgDE46u9Lg3+XoQ5ivxaPkrV7JLnvhADtCP7qH3EKV25OfptnvFhLv1plybjTSLHQxZOYkTewEwa2G3FQUspoXOO7MbwsjAIGekGZnWoux23ePmnjtQG0Q49+MmFznDsBevSAET/rLVUXKSzFhHkJ2KRi9oc4t9e8DBbmf/4Xgj8uBIRKR9Wy3f+WtV9swgGfp0F6mdxTA7x43V+Iix+YOz9C316vGLwBlGf7kFrIvmVpNz1s5MUuFrzO1/nDpgG1rwyQCvF0to9iLQh7UBs4HJth6FaW4uzW6vurK68iwa2hrMcYIdPhfxxMNMXs3cyEO7zKNn2B5OyMcezyyPJNb9MItU+dmdv/zifW5AOoEj75ScUv2ckUhO2zblfwQyokk5Ti/OJZqqpn88gW+Qb9KTVnA7Va2JIFlaUpx2ZQIzuAhabVurADFR7DYQIDP4mpkhgSkm0BTgNK9v6p4QQgOYp2MOrHolCL5kNu25rXMYLTbAv4HDm1VRMJ1tdHKMBBmWkYAc=
